"""add_is_cached_and_legendary_to_buyer_personas

Revision ID: 045994b211fd
Revises: 08afe8b48836
Create Date: 2025-04-08 09:12:33.688308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045994b211fd'
down_revision = '08afe8b48836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_session')
    op.drop_table('buyer_persona')
    op.drop_table('user_profile')
    with op.batch_alter_table('buyer_personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cached', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_legendary', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cached_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('feedback_analysis', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_user_profile_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_sessions', ['session_id'], ['id'])
        batch_op.create_foreign_key('fk_feedback_user_profile_id', 'user_profiles', ['user_profile_id'], ['id'])

    with op.batch_alter_table('name_usage_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_profile_id'], ['id'])

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_sessions', ['training_session_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_profiles', ['user_profile_id'], ['id'])

    with op.batch_alter_table('sales_stage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_profile_id'], ['id'])

    with op.batch_alter_table('session_feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('session_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_sessions', ['training_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_session', ['training_session_id'], ['id'])

    with op.batch_alter_table('session_feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_session', ['session_id'], ['id'])

    with op.batch_alter_table('sales_stage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profile', ['user_profile_id'], ['id'])

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_session', ['training_session_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_profile', ['user_profile_id'], ['id'])

    with op.batch_alter_table('name_usage_tracker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profile', ['user_profile_id'], ['id'])

    with op.batch_alter_table('feedback_analysis', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_user_profile_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'training_session', ['session_id'], ['id'])
        batch_op.create_foreign_key('fk_feedback_user_profile_id', 'user_profile', ['user_profile_id'], ['id'])

    with op.batch_alter_table('buyer_personas', schema=None) as batch_op:
        batch_op.drop_column('cached_at')
        batch_op.drop_column('is_legendary')
        batch_op.drop_column('is_cached')

    op.create_table('user_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('onboarding_complete', sa.BOOLEAN(), nullable=True),
    sa.Column('onboarding_step', sa.VARCHAR(length=50), nullable=True),
    sa.Column('onboarding_step_new', sa.INTEGER(), nullable=True),
    sa.Column('product_service', sa.TEXT(), nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('target_market', sa.VARCHAR(length=50), nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), nullable=True),
    sa.Column('experience_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pain_points', sa.TEXT(), nullable=True),
    sa.Column('recent_wins', sa.TEXT(), nullable=True),
    sa.Column('mindset_challenges', sa.TEXT(), nullable=True),
    sa.Column('improvement_goals', sa.TEXT(), nullable=True),
    sa.Column('preferred_training_style', sa.VARCHAR(length=50), nullable=True),
    sa.Column('preferred_feedback_frequency', sa.VARCHAR(length=50), nullable=True),
    sa.Column('total_roleplays', sa.INTEGER(), nullable=True),
    sa.Column('total_feedback_received', sa.INTEGER(), nullable=True),
    sa.Column('last_roleplay_date', sa.DATETIME(), nullable=True),
    sa.Column('skill_history', sa.TEXT(), nullable=True),
    sa.Column('common_objections', sa.TEXT(), nullable=True),
    sa.Column('objection_handling_scores', sa.TEXT(), nullable=True),
    sa.Column('biases_used', sa.TEXT(), nullable=True),
    sa.Column('biases_missed', sa.TEXT(), nullable=True),
    sa.Column('emotional_intelligence_score', sa.FLOAT(), nullable=True),
    sa.Column('empathy_score', sa.FLOAT(), nullable=True),
    sa.Column('active_listening_score', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('buyer_persona',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('personality_traits', sa.TEXT(), nullable=False),
    sa.Column('emotional_state', sa.VARCHAR(length=50), nullable=False),
    sa.Column('buyer_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('decision_authority', sa.VARCHAR(length=50), nullable=False),
    sa.Column('industry_context', sa.TEXT(), nullable=True),
    sa.Column('pain_points', sa.TEXT(), nullable=False),
    sa.Column('objections', sa.TEXT(), nullable=False),
    sa.Column('cognitive_biases', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_profile_id', sa.INTEGER(), nullable=True),
    sa.Column('buyer_persona_id', sa.INTEGER(), nullable=True),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('conversation_history', sa.TEXT(), nullable=True),
    sa.Column('key_moments', sa.TEXT(), nullable=True),
    sa.Column('objections_handled', sa.TEXT(), nullable=True),
    sa.Column('trust_score', sa.FLOAT(), nullable=True),
    sa.Column('persuasion_rating', sa.FLOAT(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('reached_stages', sa.TEXT(), nullable=True),
    sa.Column('current_stage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('emotional_awareness_score', sa.FLOAT(), server_default=sa.text('(70.0)'), nullable=True),
    sa.Column('empathy_score', sa.FLOAT(), server_default=sa.text('(70.0)'), nullable=True),
    sa.Column('rapport_score', sa.FLOAT(), server_default=sa.text('(70.0)'), nullable=True),
    sa.Column('question_quality_score', sa.FLOAT(), server_default=sa.text('(75.0)'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_persona_id'], ['buyer_persona.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
