"""add base_reaction_style and other pending model changes

Revision ID: 233688c62cdb
Revises: 045994b211fd
Create Date: 2025-05-18 11:20:21.721003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233688c62cdb'
down_revision = '045994b211fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_reaction_style', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('intelligence_level', sa.String(length=50), nullable=True))

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))

    with op.batch_alter_table('buyer_personas', schema=None) as batch_op:
        batch_op.drop_column('intelligence_level')
        batch_op.drop_column('base_reaction_style')

    # ### end Alembic commands ###
