"""Add business_context field to buyer_personas

Revision ID: 5581a1e99fe0
Revises: 7be1d4935550
Create Date: 2025-06-26 01:33:08.841809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5581a1e99fe0'
down_revision = '7be1d4935550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_context', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_personas', schema=None) as batch_op:
        batch_op.drop_column('business_context')

    # ### end Alembic commands ###
