"""Add legendary personas access control

Revision ID: 7be1d4935550
Revises: 6971ee351279
Create Date: 2025-06-25 23:24:15.925125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be1d4935550'
down_revision = '6971ee351279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_legendary_personas', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('has_legendary_personas')

    # ### end Alembic commands ###
