"""add call_recordings table

Revision ID: 97bcf1a30739
Revises: 5581a1e99fe0
Create Date: 2026-06-19 19:17:15.998641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bcf1a30739'
down_revision = '5581a1e99fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('emotion_analysis', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_call_recordings_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_recordings')),
    sa.UniqueConstraint('session_id', name=op.f('uq_call_recordings_session_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_recordings')
    # ### end Alembic commands ###
