"""Initial database schema

Revision ID: a71f70605ae9
Revises: 
Create Date: 2025-06-02 23:15:10.795673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71f70605ae9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_reaction_style', sa.String(length=100), nullable=True),
    sa.Column('personality_traits', sa.Text(), nullable=False),
    sa.Column('intelligence_level', sa.String(length=50), nullable=True),
    sa.Column('emotional_state', sa.String(length=50), nullable=False),
    sa.Column('buyer_type', sa.String(length=50), nullable=False),
    sa.Column('decision_authority', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('industry_context', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=False),
    sa.Column('objections', sa.Text(), nullable=False),
    sa.Column('primary_concern', sa.String(length=200), nullable=True),
    sa.Column('cognitive_biases', sa.Text(), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('longterm_personal_description', sa.Text(), nullable=True),
    sa.Column('shortterm_personal_description', sa.Text(), nullable=True),
    sa.Column('demographic_description', sa.Text(), nullable=True),
    sa.Column('linguistic_style_cue', sa.Text(), nullable=True),
    sa.Column('chattiness_level', sa.String(length=50), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=True),
    sa.Column('is_legendary', sa.Boolean(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer_personas'))
    )
    op.create_table('email_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('early_access', sa.Boolean(), nullable=True),
    sa.Column('get_updates', sa.Boolean(), nullable=True),
    sa.Column('computer_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_signups')),
    sa.UniqueConstraint('email', name=op.f('uq_email_signups_email'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('completed_roleplays', sa.Integer(), nullable=True),
    sa.Column('sales_skills', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('google_id', name=op.f('uq_user_google_id'))
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('persona_id', sa.String(length=100), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_onboarding', sa.Boolean(), nullable=True),
    sa.Column('session_setup_step', sa.String(length=50), nullable=False),
    sa.Column('product_service', sa.Text(), nullable=True),
    sa.Column('target_market', sa.String(length=50), nullable=True),
    sa.Column('sales_experience', sa.String(length=50), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_conversation_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation'))
    )
    op.create_table('feature_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_id_voted_for', sa.String(length=100), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_feature_vote_user_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_vote'))
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('initial_setup_complete', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.String(length=50), nullable=True),
    sa.Column('onboarding_step_new', sa.Integer(), nullable=True),
    sa.Column('product_service', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('target_market', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('recent_wins', sa.Text(), nullable=True),
    sa.Column('mindset_challenges', sa.Text(), nullable=True),
    sa.Column('improvement_goals', sa.Text(), nullable=True),
    sa.Column('preferred_training_style', sa.String(length=50), nullable=True),
    sa.Column('preferred_feedback_frequency', sa.String(length=50), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('total_roleplays', sa.Integer(), nullable=True),
    sa.Column('total_feedback_received', sa.Integer(), nullable=True),
    sa.Column('last_roleplay_date', sa.DateTime(), nullable=True),
    sa.Column('skill_history', sa.Text(), nullable=True),
    sa.Column('common_objections', sa.Text(), nullable=True),
    sa.Column('objection_handling_scores', sa.Text(), nullable=True),
    sa.Column('biases_used', sa.Text(), nullable=True),
    sa.Column('biases_missed', sa.Text(), nullable=True),
    sa.Column('emotional_intelligence_score', sa.Float(), nullable=True),
    sa.Column('empathy_score', sa.Float(), nullable=True),
    sa.Column('active_listening_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_profiles_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('skill_scores', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_feedback_conversation_id_conversation')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_feedback_user_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('conversation_id', name=op.f('uq_feedback_conversation_id'))
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_message_conversation_id_conversation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_table('name_usage_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name=op.f('fk_name_usage_tracker_user_profile_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_name_usage_tracker'))
    )
    op.create_table('sales_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name=op.f('fk_sales_stage_user_profile_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_stage'))
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('session_length', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('reached_stages', sa.Text(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('persuasion_rating', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('conversation_json', sa.Text(), nullable=True),
    sa.Column('current_turn', sa.Integer(), nullable=True),
    sa.Column('discovery_score', sa.Float(), nullable=True),
    sa.Column('solution_score', sa.Float(), nullable=True),
    sa.Column('objection_score', sa.Float(), nullable=True),
    sa.Column('closing_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('emotional_awareness_score', sa.Float(), nullable=True),
    sa.Column('empathy_score', sa.Float(), nullable=True),
    sa.Column('rapport_score', sa.Float(), nullable=True),
    sa.Column('question_quality_score', sa.Float(), nullable=True),
    sa.Column('feedback_json', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('areas_to_improve', sa.Text(), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('buyer_persona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_persona_id'], ['buyer_personas.id'], name=op.f('fk_training_sessions_buyer_persona_id_buyer_personas')),
    sa.ForeignKeyConstraint(['persona_id'], ['buyer_personas.id'], name=op.f('fk_training_sessions_persona_id_buyer_personas')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_training_sessions_user_id_user_profiles')),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name=op.f('fk_training_sessions_user_profile_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_sessions'))
    )
    op.create_table('feedback_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('overall_assessment', sa.Text(), nullable=True),
    sa.Column('strengths_demonstrated', sa.Text(), nullable=True),
    sa.Column('areas_for_improvement', sa.Text(), nullable=True),
    sa.Column('rapport_feedback', sa.Text(), nullable=True),
    sa.Column('discovery_feedback', sa.Text(), nullable=True),
    sa.Column('objection_feedback', sa.Text(), nullable=True),
    sa.Column('closing_feedback', sa.Text(), nullable=True),
    sa.Column('emotional_intelligence_feedback', sa.Text(), nullable=True),
    sa.Column('question_quality_feedback', sa.Text(), nullable=True),
    sa.Column('emotional_awareness_score', sa.Float(), nullable=True),
    sa.Column('empathy_score', sa.Float(), nullable=True),
    sa.Column('rapport_score', sa.Float(), nullable=True),
    sa.Column('question_quality_score', sa.Float(), nullable=True),
    sa.Column('insufficient_data', sa.Boolean(), nullable=True),
    sa.Column('mindset_insights', sa.Text(), nullable=True),
    sa.Column('limiting_beliefs_detected', sa.Text(), nullable=True),
    sa.Column('reframe_suggestions', sa.Text(), nullable=True),
    sa.Column('action_items', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('fk_feedback_analysis_session_id_training_sessions')),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name='fk_feedback_user_profile_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_analysis'))
    )
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('rapport_building', sa.Float(), nullable=False),
    sa.Column('needs_discovery', sa.Float(), nullable=False),
    sa.Column('objection_handling', sa.Float(), nullable=False),
    sa.Column('closing_techniques', sa.Float(), nullable=False),
    sa.Column('product_knowledge', sa.Float(), nullable=False),
    sa.Column('bias_effectiveness', sa.Text(), nullable=False),
    sa.Column('emotional_awareness', sa.Float(), nullable=False),
    sa.Column('tone_consistency', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], name=op.f('fk_performance_metrics_training_session_id_training_sessions')),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name=op.f('fk_performance_metrics_user_profile_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_metrics'))
    )
    op.create_table('session_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('persona_rating', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], name=op.f('fk_session_feedback_session_id_training_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_feedback'))
    )
    op.create_table('session_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('talk_ratio', sa.Float(), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('question_ratio', sa.Float(), nullable=True),
    sa.Column('filler_word_count', sa.Integer(), nullable=True),
    sa.Column('technical_term_count', sa.Integer(), nullable=True),
    sa.Column('positive_language_ratio', sa.Float(), nullable=True),
    sa.Column('mirroring_score', sa.Float(), nullable=True),
    sa.Column('time_small_talk', sa.Float(), nullable=True),
    sa.Column('time_discovery', sa.Float(), nullable=True),
    sa.Column('time_pitch', sa.Float(), nullable=True),
    sa.Column('time_objection_handling', sa.Float(), nullable=True),
    sa.Column('time_closing', sa.Float(), nullable=True),
    sa.Column('discovery_pitch_ratio', sa.Float(), nullable=True),
    sa.Column('first_objection_time', sa.Float(), nullable=True),
    sa.Column('objections_handled_count', sa.Integer(), nullable=True),
    sa.Column('closing_attempts', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('avg_prospect_response_length', sa.Float(), nullable=True),
    sa.Column('pain_points_identified', sa.Integer(), nullable=True),
    sa.Column('value_proposition_alignment', sa.Float(), nullable=True),
    sa.Column('pain_point_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], name=op.f('fk_session_metrics_training_session_id_training_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_metrics'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_metrics')
    op.drop_table('session_feedback')
    op.drop_table('performance_metrics')
    op.drop_table('feedback_analysis')
    op.drop_table('training_sessions')
    op.drop_table('sales_stage')
    op.drop_table('name_usage_tracker')
    op.drop_table('message')
    op.drop_table('feedback')
    op.drop_table('user_profiles')
    op.drop_table('feature_vote')
    op.drop_table('conversation')
    op.drop_table('user')
    op.drop_table('email_signups')
    op.drop_table('buyer_personas')
    # ### end Alembic commands ###
