"""Add detailed fields to BuyerPersona

Revision ID: d74e8e5af01d
Revises: 233688c62cdb
Create Date: 2025-05-19 16:27:27.831365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74e8e5af01d'
down_revision = '233688c62cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('longterm_personal_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shortterm_personal_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('demographic_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('linguistic_style_cue', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chattiness_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_personas', schema=None) as batch_op:
        batch_op.drop_column('chattiness_level')
        batch_op.drop_column('linguistic_style_cue')
        batch_op.drop_column('demographic_description')
        batch_op.drop_column('shortterm_personal_description')
        batch_op.drop_column('longterm_personal_description')
        batch_op.drop_column('business_description')

    # ### end Alembic commands ###
