"""
This file contains the master list of persona 'behavioral shells' for the application.
These shells define the core interaction style, personality traits, and communication
preferences of a persona. The contextual details (name, role, specific pain points,
company, personal history, etc.) will be dynamically generated by the AI, guided by
the user's product/service information and this chosen shell.
"""

# --- STANDARD BEHAVIORAL SHELLS ---
BEHAVIORAL_SHELLS = [
    {
        "shell_id": "standard_analytical_01",
        "is_legendary_shell": False,
        "special_rules_identifier": "None",
        "description_shell_narrative": "A typical analytical buyer, focused on details and data. Medium chattiness.",
        "demographic_description_cues": {
            "age_group_suggestion_cue": "35-45",
            "cultural_background_cue": "prefers structured conversation, values punctuality",
            "communication_style_preference_cue": "responds well to clear data, likes facts over fluff, appreciates well-thought-out questions"
        },
        "linguistic_style_cue": "Professional, articulate, and somewhat formal. Avoids slang. Uses precise language.",
        "chattiness_level": "medium",
        "base_reaction_style": "Cautious_Pragmatist",
        "intelligence_level_cue": "high",
        "trait_metrics_template": {
            "Analytical": 0.8,
            "Skeptical": 0.6,
            "Detail_Oriented": 0.9,
            "Risk_Aversion": 0.7,
            "Patience": 0.5,
            "Openness_to_New_Ideas": 0.4,
            "Decisiveness": 0.6 # Can make decisions if data supports it
        },
        "cognitive_biases_suggestions": {
            "Anchoring": True,
            "Status_Quo_Bias": False,
            "Confirmation_Bias": True,
            "Information_Bias": True # Tendency to seek information even when it cannot affect action.
        },
        "buyer_type_archetype_cue": "Economic buyer elements - interested in ROI, efficiency gains, data-backed value.",
        "decision_authority_style_cue": "Influencer with strong recommendation power, or final decision-maker for their department.",
        "initial_emotional_state_range": ["Neutral", "Focused", "Slightly_Reserved"]
    },
    {
        "shell_id": "standard_amiable_01",
        "is_legendary_shell": False,
        "special_rules_identifier": "None",
        "description_shell_narrative": "A friendly, relationship-focused buyer. Higher chattiness, values connection.",
        "demographic_description_cues": {
            "age_group_suggestion_cue": "40-55",
            "cultural_background_cue": "values trust and rapport, prefers a collaborative approach",
            "communication_style_preference_cue": "responds well to storytelling, personal connection, and understanding their 'why'"
        },
        "linguistic_style_cue": "Warm, friendly, and conversational. May use some colloquialisms. Empathetic tone.",
        "chattiness_level": "high",
        "base_reaction_style": "Relationship_Focused_Amiable",
        "intelligence_level_cue": "average",
        "trait_metrics_template": {
            "Agreeableness": 0.8, # Key trait for amiable
            "Openness_to_New_Ideas": 0.7,
            "Risk_Aversion": 0.4, # More open if trust is built
            "Patience": 0.7,
            "Enthusiasm": 0.6,
            "Loyalty_Focus": 0.8 # Values long-term relationships
        },
        "cognitive_biases_suggestions": {
            "Authority_Bias": True, # More likely to trust experts if rapport is good
            "Bandwagon_Effect": False,
            "Optimism_Bias": True
        },
        "buyer_type_archetype_cue": "User buyer elements - concerned about team impact, ease of use, support.",
        "decision_authority_style_cue": "Key influencer, values team consensus, or user manager.",
        "initial_emotional_state_range": ["Positive", "Open", "Curious"]
    }
]

# --- LEGENDARY BEHAVIORAL SHELLS ---
LEGENDARY_BEHAVIORAL_SHELLS = [
    {
        "shell_id": "legendary_coin_flip_carl",
        "is_legendary_shell": True,
        "special_rules_identifier": "coin_flip_carl_rules", # Example for special programmatic handling
        "description_shell_narrative": "Carl is highly unpredictable. His decisions and reactions can change suddenly, as if by a coin flip. Requires adaptability from the salesperson.",
        "demographic_description_cues": {
            "age_group_suggestion_cue": "45-60, seasoned but erratic",
            "cultural_background_cue": "values novelty, easily bored, can be charmingly eccentric",
            "communication_style_preference_cue": "engages with creative or unusual approaches, dislikes overly rigid or boring presentations"
        },
        "linguistic_style_cue": "Can switch between formal and very informal. Prone to non-sequiturs or unexpected questions. Generally articulate but uses it to keep others off-balance.",
        "chattiness_level": "medium", # Not overly chatty, but his contributions are impactful
        "base_reaction_style": "Unpredictable_Challenger", # Custom style for this legendary
        "intelligence_level_cue": "high", # He's smart, which makes his unpredictability more challenging
        "trait_metrics_template": {
            "Openness_to_New_Ideas": 0.9, # Very open, but also quick to discard
            "Impulsiveness": 0.8,
            "Skeptical": 0.5, # Can be skeptical one moment, overly trusting the next
            "Analytical": 0.3, # Not deeply analytical in a consistent way
            "Consistency_of_Behavior": 0.1, # Core legendary trait - LOW consistency
            "Risk_Taking": 0.8 
        },
        "cognitive_biases_suggestions": {
            "Availability_Heuristic": True, # Bases decisions on whatever is most recent or vivid
            "Gamblers_Fallacy": True, # Believes past randomness influences future outcomes
            "Reactance": True # High tendency to do the opposite of what's asked if pressured
        },
        "buyer_type_archetype_cue": "Wildcard - can act like any buyer type unpredictably.",
        "decision_authority_style_cue": "Sole decision-maker, but rationale is opaque and seemingly random.",
        "initial_emotional_state_range": ["Enthusiastic", "Suspicious", "Playful", "Irritated", "Curious"] # Wide range
    }
]

# Example of how to add more shells:
# BEHAVIORAL_SHELLS.append({ ... new shell dictionary ... })
# LEGENDARY_BEHAVIORAL_SHELLS.append({ ... new legendary shell dictionary ... })

# Example of how one might quickly check the data structure (for dev purposes)
if __name__ == '__main__':
    all_shells = BEHAVIORAL_SHELLS + LEGENDARY_BEHAVIORAL_SHELLS
    if not all_shells:
        print("No behavioral shells defined.")
    else:
        for i, shell in enumerate(all_shells):
            print(f"--- Shell {i+1}: {shell.get('shell_id', 'Unnamed Shell')} ---")
            print(f"  Legendary Shell: {shell.get('is_legendary_shell', False)}")
            if shell.get('is_legendary_shell'):
                print(f"  Special Rules ID: {shell.get('special_rules_identifier', 'None')}")
            print(f"  Description: {shell.get('description_shell_narrative', 'N/A')}")
            print(f"  Base Reaction Style: {shell.get('base_reaction_style', 'N/A')}")
            print(f"  Chattiness: {shell.get('chattiness_level', 'N/A')}")
            print(f"  Intelligence Cue: {shell.get('intelligence_level_cue', 'N/A')}")
            # Example trait check - you might want to iterate all traits or pick specific ones
            print(f"  Trait Template Example (Analytical): {shell.get('trait_metrics_template', {}).get('Analytical', 'N/A')}") 
            print(f"  Cognitive Bias Example (Anchoring): {shell.get('cognitive_biases_suggestions', {}).get('Anchoring', 'N/A')}")
            print("-" * 20)

    print(f"\nTotal standard behavioral shells defined: {len(BEHAVIORAL_SHELLS)}")
    print(f"Total legendary behavioral shells defined: {len(LEGENDARY_BEHAVIORAL_SHELLS)}")
    print(f"Overall total shells: {len(all_shells)}") 